library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/main/urls.py
# pylint: skip-file
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.login_page, name='login_page'),
    url(r'^search/$', views.search, name='search'),

    path('authors/<author_id>/', views.CompositionsView.as_view(), name='compositions'),
    path('composition/<composition_id>', views.translations, name='translations'),
    path('translation/<translation_id>', views.show_translation, name='show_translation'),
]

library/main/models.py
# pylint: disable=too-few-public-methods, no-member, missing-function-docstring, missing-class-docstring
"""
App models:
- Author - instance of composition's author
- Composition - instance of composition that can have translation
- Translation - Instance of composition's translation
"""
from django.db import models
from django.conf import settings

LANGUAGES = [
        ('ru', 'Русский'),
        ('en', 'Английский'),
        ('de', 'Немецкий'),
        ('fr', 'Французский')
    ]


class Author(models.Model):
    name = models.CharField('Автор', max_length=100)
    info = models.TextField('Биография', default='')
    image = models.ImageField(upload_to='authors', default='authors/unnamed.jpg')

    def __repr__(self):
        return f'<Author: {self.name}>'

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Composition(models.Model):
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        verbose_name='Автор')
    name = models.CharField('Автор', max_length=100)
    text = models.TextField('Оригинал', default='')
    lang = models.CharField('Язык оригинала', max_length=100, choices=LANGUAGES, default='ru')

    def __repr__(self):
        return f'<Composition: {self.name}>'

    def __str__(self):
        return f'{self.name}'

    @staticmethod
    def get_by_author(author_id: int) -> list:
        return list(Composition.objects.filter(author__id=author_id))

    class Meta:
        verbose_name = 'Произведение'
        verbose_name_plural = 'Произведения'


class Translation(models.Model):
    composition = models.ForeignKey(
        Composition,
        on_delete=models.CASCADE,
        verbose_name='Произведение')
    translation_author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Автор')
    text = models.TextField('Перевод')
    lang = models.CharField('Язык', max_length=100, choices=LANGUAGES, default='ru')

    def __repr__(self):
        return f'<Translation: {self.composition.name} on {self.lang}>'

    def __str__(self):
        return f'Перевод {self.composition.name} на {self.lang}, автор -  {self.translation_author}'

    @staticmethod
    def get_by_composition(composition_id: int) -> list:
        return list(Translation.objects.filter(composition__id=composition_id))

    class Meta:
        verbose_name = 'Перевод'
        verbose_name_plural = 'Переводы'

library/main/forms.py
# pylint: disable=too-few-public-methods, no-member, missing-function-docstring, missing-class-docstring
"""
App models' forms:
- BaseForm - set 'form-control' class for all fields (except 'image' field)
- AuthorForm
- CompositionForm
- TranslationForm
"""
from django import forms
from .models import LANGUAGES, Author


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name != 'image':
                visible.field.widget.attrs['class'] = 'form-control'


class AuthorForm(BaseForm):
    name = forms.CharField(label='Имя', max_length=100)
    info = forms.CharField(label='Справка', widget=forms.Textarea)
    image = forms.ImageField(label='Фотография', required=False)


class CompositionForm(BaseForm):
    author = forms.ModelChoiceField(label='Автор', queryset=Author.objects.all())
    name = forms.CharField(label='Название')
    text = forms.CharField(label='Оригинал', widget=forms.Textarea)
    lang = forms.ChoiceField(label='Язык оригинала', choices=LANGUAGES)

    def get_author(self):
        return Author.objects.get(id=int(self.cleaned_data['author']))

    def get_lang(self):
        lang_dict = dict(LANGUAGES)
        return lang_dict[self.cleaned_data['lang']]


class TranslationForm(BaseForm):
    text = forms.CharField(label='Текст перевода', widget=forms.Textarea)
    lang = forms.ChoiceField(label='Язык перевода', choices=LANGUAGES)

    def get_lang(self):
        lang_dict = dict(LANGUAGES)
        return lang_dict[self.cleaned_data['lang']]

library/main/views.py
# pylint: disable=no-member
"""Web-library backend"""
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views import View
from django.utils.decorators import method_decorator
from .decorators import unauthenticated_user
from .models import Author, Composition, Translation
from .forms import AuthorForm, CompositionForm, TranslationForm


class IndexView(View):
    """Main page view - '/'"""
    template = 'main/main.html'
    title = 'Главная страница | Библиотека'
    context = {}

    @method_decorator(unauthenticated_user)
    def dispatch(self, *args, **kwargs):
        """Displays page for authenticated users only"""
        return super().dispatch(*args, **kwargs)

    @staticmethod
    def get_authors_list():
        """Get list of tuples each containing 1-3 Authors"""
        authors = Author.objects.all()
        authors_list = list(zip(*[iter(authors)] * 3))
        authors_list += [authors[len(authors_list) * 3:]]
        return authors_list

    def add_author(self):
        """Add author to DB"""
        author_form = self.context['author_form']
        if author_form.is_valid():
            name = author_form.cleaned_data["name"]
            Author.objects.create(
                name=name,
                info=author_form.cleaned_data["info"],
                image=author_form.cleaned_data["image"])
            self.context['success'] = f'Автор {name} был успешно добавлен в базу.'
        else:
            self.context['error'] = 'Форма некоректно заполнена.'

    def add_composition(self):
        """Add composition to DB"""
        comp_form = self.context['comp_form']
        if comp_form.is_valid():
            name = comp_form.cleaned_data["name"]
            Composition.objects.create(
                author=comp_form.cleaned_data["author"],
                name=name,
                text=comp_form.cleaned_data["text"],
                lang=comp_form.get_lang())
            self.context['success'] = f"Произведение '{name}' было успешно добавлено в базу."
        else:
            self.context['error'] = 'Форма некоректно заполнена.'

    def get(self, request):
        """Main page - get method"""
        self.context = {
            'title': self.title,
            'authors_list': IndexView.get_authors_list(),
            'author_form': AuthorForm(),
            'comp_form': CompositionForm()
        }
        return render(request, self.template, self.context)

    def post(self, request):
        """Main page - post method"""
        self.context = {
            'title': self.title,
            'authors_list': IndexView.get_authors_list(),
            'author_form': AuthorForm(request.POST, request.FILES),
            'comp_form': CompositionForm(request.POST)
        }
        if 'add_author' in request.POST:
            self.add_author()
        if 'add_composition' in request.POST:
            self.add_composition()
        return render(request, self.template, self.context)


class CompositionsView(View):
    """Compositions page view - 'composition/<composition_id>'"""
    template = 'main/compositions.html'
    title = 'Главная страница | Библиотека'
    context = {}

    @method_decorator(unauthenticated_user)
    def dispatch(self, *args, **kwargs):
        """Displays page for authenticated users only"""
        return super().dispatch(*args, **kwargs)

    def add_translation(self, request):
        """Add translation to DB"""
        form = self.context['form']
        if form.is_valid():
            composition = Composition.objects.get(id=request.POST['composition_id'])
            author = User.objects.get(id=request.POST['author_id'])
            Translation.objects.create(
                composition=composition,
                text=form.cleaned_data["text"],
                translation_author=author,
                lang=form.get_lang())
            self.context['success'] = 'Перевод был успешно добавлен.'
        else:
            self.context['error'] = 'Форма некоректно заполнена.'

    def get(self, request, author_id):
        """Compositions page - get method"""
        form = TranslationForm()
        self.context = {
            'title': f'{Author.objects.get(id=author_id)} | Библиотека',
            'compositions': Composition.get_by_author(author_id),
            'author': Author.objects.get(id=author_id),
            'form': form
        }
        return render(request, self.template, self.context)

    def post(self, request, author_id):
        """Compositions page - post method"""
        form = TranslationForm(request.POST)
        self.context = {
            'title': f'{Author.objects.get(id=author_id)} | Библиотека',
            'compositions': Composition.get_by_author(author_id),
            'author': Author.objects.get(id=author_id),
            'form': form
        }
        if 'add_translation' in request.POST:
            self.add_translation(request)
        return render(request, self.template, self.context)


def login_page(request):
    """
    In case of successful authorization redirect to main page
    else displays login page with error
    """
    logout(request)
    if 'username' not in request.POST or 'password' not in request.POST:
        return render(request, 'main/login.html')
    user = authenticate(
        username=request.POST['username'],
        password=request.POST['password'])
    if user is not None:
        if user.is_active:
            login(request, user)
            return redirect('/')
        context = {'error': 'Ошибка: аккаунт пользователя отключен!'}
        return render(request, 'main/login.html', context)
    context = {'error': 'Ошибка: неправильное имя пользователя или пароль!'}
    return render(request, 'main/login.html', context)


@unauthenticated_user
def search(request):
    """
    Search compositions by string query
    """
    if request.method == "POST":
        query = request.POST['q']
        context = {
            'title': 'Результаты поиска | Библиотека',
            'compositions': Composition.objects.filter(name__contains=query),
            'q': query
        }
        return render(request, 'main/search.html', context)

    return redirect('/')


@unauthenticated_user
def translations(request, composition_id):
    """
    Displays all Composition(id=composition_id)'s translations
    """
    context = {
        'title': 'Переводы | Библиотека',
        'translations': Translation.get_by_composition(composition_id),
        'composition': Composition.objects.get(id=composition_id)
    }
    return render(request, 'main/translations.html', context)


@unauthenticated_user
def show_translation(request, translation_id):
    """
    Displays Translation(id=translation_id)
    """
    translation = Translation.objects.get(id=translation_id)
    context = {
        'title': 'Перевод | Библиотека',
        'translation': translation,
    }
    return render(request, 'main/show_translation.html', context)

library/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Leadness, 2020 -->
    <!-- https://github.com/LeadNess/web-library -->
    
    <title>{{ title }}</title>
    
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'main/css/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/modal-window.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/search-header.css' %}" rel="stylesheet">

    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">

  </head>

<body id='body'>
  <header>
    <div class="bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">Поиск</h4>
            <p class="text-muted">Поиск осуществляется по всем произведениям, которые содержатся в базе библиотеки.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <form action="{% url 'main:search' %}" method='post' class="form-inline my-2 my-lg-0">
              {% csrf_token %}
              <input class="form-control mr-sm-2" name='q' type="text" placeholder="Поиск по произведениям" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="d-flex justify-content-between">
        <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
          <img src="{% static 'favicon/favicon-96x96.png' %}" width="20" height="20" class="mr-2">
          <strong>Библиотека переводов</strong>
        </a>
      </div>
      <div class="d-flex justify-content-between">
        <a href="" class="navbar-brand d-flex align-items-center">{{ user.username }}</a>
        <a href="{% url 'main:login_page' %}" class="navbar-brand d-flex align-items-center">Выйти</a>
        <button class="navbar-toggler" type="button" onclick="displaySearchHeader()">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <main role="main">
  {% block content %}
  {% endblock content %}
  </main>

</body>

<script src="{% static 'main/js/modal-window.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
<script type="text/javascript">
    let body = document.getElementById('body');
    let counter = 0;
    document.getElementById('navbarHeader').style.display = "none";
</script>

</html>

library/templates/main/compositions.html
{% extends "main/base.html" %}

{% block content %}

{% load static %}

<section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">{{ author.name }}</h1>
      <p class="lead text-muted">{{ author.info }}</p>
    </div>
</section>

</div>
{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>                    
{% endif %}
{% if success %}
<div class="alert alert-success" role="alert">
    {{ success }}
</div>                    
{% endif %}

<div class="album py-5 bg-light">
  <div class="container">

      <div>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Название</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          {% for composition in compositions %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ composition.name }}</td>
            <td><a type="button" href="{% url 'main:translations' composition.id %}" class="btn btn-primary btn-sm">Показать переводы</a></td>
            <td><a type="button" href="#" data-modal="translation-modal" onclick="setComposition({{ composition.id }}, '{{ composition.name }}')" class="btn btn-secondary btn-sm js-open-modal">Добавить перевод</a></td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>

  </div>
</div>

<div class="modal-window" data-modal="translation-modal">
   <img class="modal__cross js-modal-close" src="{% static 'main/image/close.svg' %}">
   <h4 id='header'>Новый перевод</h4>
   <hr class="my hr4">
    <form action="{{ request.path }}" method="post">
    {% csrf_token %}
      <div>
        <label for="{{ form.lang.id_for_label }}">Язык перевода<br>
        {{ form.lang }}
        </label>
      </div>
      <div>
        <label for="{{ form.text.id_for_label }}">Перевод<br>
        {{ form.text }}
        </label>
      </div>
      <input type="hidden" id="composition_id" name="composition_id" value="">
      <input type="hidden" name="author_id" value="{{ request.user.id }}">                   
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary js-modal-close">Отмена</button>
        <input type="submit" name="add_translation" value="Добавить" class="btn btn-outline-primary my-2">
      </div>
    </form>
</div>

<div class="overlay js-overlay-modal"></div>

<script src="{% static 'main/js/compositions.js' %}"></script>

{% endblock %}

library/templates/main/login.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Leadness, 2020 -->
        <!-- https://github.com/LeadNess/web-library -->

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	{% load static %}
        <link rel="stylesheet" href="{% static 'main/css/sidebar.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">

        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">

    <title>Войти | Библиотека</title>
    </head>
    <body>
        <div class="row justify-content-center">
            <h1 style="color: white; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">Библиотека переводов</h1>
        </div>
        <main class="login-form">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">Войти в систему</div>
                            {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>                    
                            {% endif %}
                            <div class="card-body">
                                <form action="{% url 'main:login_page' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label for="username" class="col-md-4 col-form-label text-md-right">Учетная запись</label>
                                        <div class="col-md-6">
                                            <input type="text" id="username" class="form-control" name="username" required autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password" class="col-md-4 col-form-label text-md-right">Пароль</label>
                                        <div class="col-md-6">
                                            <input type="password" id="password" class="form-control" name="password" required>
                                        </div>
                                    </div>

                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            Авторизироваться
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

    </body>
</html>

library/templates/main/main.html
{% extends "main/base.html" %}

{% block content %}

{% load static %}

 	<section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Библиотека переводов</h1>
      <p class="lead text-muted">Библиотека переводов - это не просто тупое название. Это возможность поделиться со всеми своими переводами произведений любимых авторов.</p>
      <p>
        <a href="#" data-modal="author-modal" class="btn btn-primary my-2 js-open-modal">Добавить автора</a>
        <a href="#" data-modal="composition-modal" class="btn btn-primary my-2 js-open-modal">Добавить произведение</a>
      </p>
    </div>
  </section>

  </div>
  {% if error %}
  <div class="alert alert-danger" role="alert">
      {{ error }}
  </div>                    
  {% endif %}
  {% if success %}
  <div class="alert alert-success" role="alert">
      {{ success }}
  </div>                    
  {% endif %}

  <div class="album py-5 bg-light">
    <div class="container">
    {% for authors in authors_list %}

      <div class="row">

      	{% for author in authors %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            {% if author.image %}
            <img class="card-img-top" src="{{ author.image.url }}" height="400" width="100" alt="Card image cap">
            {% else %}
            <img class="card-img-top" src="/media/authors/unnamed.jpg" height="400" width="100" alt="Card image cap">
            {% endif %}
            <div class="card-body">
              <p class="card-text">{{ author.name }}</p>
              <p class="card-text">{{ author.info }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main:compositions' author.id %}" class="btn btn-sm btn-outline-secondary">Произведения</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>

    {% endfor %}
    </div>
  </div>

  <div class="modal-window" data-modal="author-modal">
   <img class="modal__cross js-modal-close" src="{% static 'main/image/close.svg' %}">
   <h4>Новый автор</h4>
   <p class="lead text-muted">Добавьте нового автора, чтобы иметь возможности добавлять переводы его произведений.</p>
   <hr class="my hr4">
    <form action="{% url 'main:index' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
          <label for="{{ form.name.id_for_label }}">Имя<br>
            {{ author_form.name }}
          </label>
          <label for="{{ form.info.id_for_label }}">Справка<br>
            {{ author_form.info }}
          </label>
          <label for="{{ form.image.id_for_label }}">Изображение<br>
            {{ author_form.image }}
          </label>         
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary js-modal-close">Отмена</button>
        <input type="submit" name="add_author" value="Добавить" class="btn btn-outline-primary my-2"> 
      </div>
    </form>
  </div>

<div class="modal-window" data-modal="composition-modal">
   <img class="modal__cross js-modal-close" src="{% static 'main/image/close.svg' %}">
   <h4>Новое произведение</h4>
   <p class="lead text-muted">Добавьте произведение, чтобы иметь возможность добавлять его переводы.</p>
   <hr class="my hr4">
    <form action="{% url 'main:index' %}" method="post">
    {% csrf_token %}
      <div>
        <label for="{{ form.name.id_for_label }}">Имя<br>
        {{ comp_form.name }}
        </label>
      </div>
      <div>
        <label for="{{ form.author.id_for_label }}">Автор<br>
        {{ comp_form.author }}
        </label>
      </div>
      <div>
        <label for="{{ form.text.id_for_label }}">Оригинал<br>
        {{ comp_form.text }}
        </label>
      </div>
      <div>
        <label for="{{ form.lang.id_for_label }}">Язык оригинала<br>
        {{ comp_form.lang }}
        </label>  
      </div>         
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary js-modal-close">Отмена</button>
        <input type="submit" name="add_composition" value="Добавить" class="btn btn-outline-primary my-2">
      </div>
    </form>
</div>

<!-- Подложка под модальным окном -->
<div class="overlay js-overlay-modal"></div>

{% endblock %}

library/templates/main/search.html
{% extends "main/base.html" %}

{% block content %}

  {% if compositions %}
  <section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Результаты поиска</h1>
      <p class="lead text-muted">По запросу '{{ q }}' были найдены следующие произведения:</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

        <div>
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Название</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            {% for composition in compositions %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ composition.name }}</td>
              <td><a type="button" href="{% url 'main:translations' composition.id %}" class="btn btn-primary btn-sm">Показать переводы</a></td>
              <td><a type="button" href="{% url 'main:compositions' composition.author.id %}" class="btn btn-secondary btn-sm">Перейти к автору</a></td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>

    </div>
  </div>
  {% else %}    
  <section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Результаты поиска</h1>
      <p class="lead text-muted">Произведения по запросу '{{ q }}' не были найдены.</p>
    </div>
  </section>
  {% endif %}

{% endblock %}

library/templates/main/show_translation.html
{% extends "main/base.html" %}

{% block content %}
<section class="text-center">
  <div class="container">
    <h1 class="jumbotron-heading">{{ translation.composition.name }}</h1>
    <p class="lead text-muted">Автор перевода - {{ translation.translation_author }}.</p>
  </div>
</section>

<div class="album py-5 bg-light">

  <div class="d-flex justify-content-center">

    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <p class="card-text"><strong>Перевод</strong></p>
          <p class="card-text" style="white-space: pre-line">{{ translation.text }}</p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <p class="card-text"><strong>Оригинал</strong></p>
          <p class="card-text" style="white-space: pre-line">{{ translation.composition.text }}</p>
        </div>
      </div>
    </div>

  </div>

</div>
{% endblock %}

library/templates/main/show_translations.html
{% extends "main/base.html" %}

{% block content %}
<section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">{{ composition.name }}</h1>
      <p class="lead text-muted">Язык оригинала - {{ composition.lang }}</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

        <div>
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Автор</th>
                <th>Язык</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            {% for translation in translations %}
            
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ translation.translation_author }}</td>
                <td>{{ translation.lang }}</td>
                <td><a href="{% url 'main:show_translation' translation.id %}" class="btn btn-secondary btn-sm">Просмотреть</a></td>
              </tr>
            
            {% endfor %}
            </tbody>
          </table>
        </div>

    </div>
  </div>
{% endblock %}

library/templates/main/translations.html
{% extends "main/base.html" %}

{% block content %}
<section class="text-center">
    <div class="container">
      <h1 class="jumbotron-heading">{{ composition.name }}</h1>
      <p class="lead text-muted">Язык оригинала - {{ composition.lang }}</p>
    </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

      <div>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Автор</th>
              <th>Язык</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          {% for translation in translations %}
          
            <tr title='{{ translation.text }}'>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ translation.translation_author }}</td>
              <td>{{ translation.lang }}</td>
              <td><a href="{% url 'main:show_translation' translation.id %}" class="btn btn-secondary btn-sm">Просмотреть</a></td>
            </tr>
          
          {% endfor %}
          </tbody>
        </table>
      </div>

  </div>
</div>
{% endblock %}